# Generated by Django 5.2.4 on 2024-07-01
from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=500)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('math', models.FloatField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], null=False)),
                ('french', models.FloatField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], null=False)),
                ('anglais', models.FloatField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], null=False)),
            ],
        ),
    ] 