# Generated by Django 5.2.4 on 2025-07-04 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='anglais',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='français',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='math',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
