# Generated by Django 5.2.4 on 2025-07-07 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0002_students_anglais_students_français_students_math_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='français',
        ),
        migrations.AlterField(
            model_name='students',
            name='anglais',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='math',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
